apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongo-config
data:
    mongod.conf: |
        sharding:
            clusterRole: configsvr
        replication:
            replSetName: cfgrs
        net:
            bindIpAll: true
            port: 27017
        security:
            keyFile: /etc/mongokey